config/routes.rb
Rails.application.routes.draw do
  devise_for :hackers
  get 'home/index'

  root 'home#index'

end

app/models/hacker.rb
class Hacker < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<p>Welcome to railsTemplate</p> <!-- rspec spec/features/home_spec.rb -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTemplate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- devise -->
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= link_to('Sign in', new_hacker_session_path)  %>

<%= yield %>

</body>
</html>